CREATE TABLE SB_TB_VACCINE (
                               id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               name VARCHAR2(255) NOT NULL,
                               species VARCHAR2(255),
                               description VARCHAR2(500),
                               first_dose_age_months NUMBER(10) NOT NULL,
                               booster_interval_months NUMBER(10),
                               CONSTRAINT pk_vaccine PRIMARY KEY (id)
);

CREATE TABLE SB_TB_ANIMAL_VACCINATION (
                                          id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          application_date VARCHAR2(255) NOT NULL,
                                          animal_id NUMBER(10) NOT NULL,
                                          vaccine_id NUMBER(10) NOT NULL,
                                          CONSTRAINT pk_animal_vaccination PRIMARY KEY (id),
                                          CONSTRAINT fk_animal_vaccination_animal
                                              FOREIGN KEY (animal_id) REFERENCES SB_TB_ANIMAL(id),
                                          CONSTRAINT fk_animal_vaccination_vaccine
                                              FOREIGN KEY (vaccine_id) REFERENCES SB_TB_VACCINE(id)
);

INSERT INTO SB_TB_VACCINE (name, species, description, first_dose_age_months, booster_interval_months)
VALUES ('V8 / V10 (Polivalente)', 'Cão', 'Protege contra cinomose, parvovirose, hepatite, leptospirose e outras doenças.', 2, 12);

INSERT INTO SB_TB_VACCINE (name, species, description, first_dose_age_months, booster_interval_months)
VALUES ('Antirrábica', NULL, 'Protege contra a raiva. Recomendada para cães e gatos.', 3, 12);

INSERT INTO SB_TB_VACCINE (name, species, description, first_dose_age_months, booster_interval_months)
VALUES ('Gripe Canina (Tosse dos Canis)', 'Cão', 'Protege contra os agentes da traqueobronquite infecciosa canina.', 2, 12);

INSERT INTO SB_TB_VACCINE (name, species, description, first_dose_age_months, booster_interval_months)
VALUES ('Giárdia', NULL, 'Protege contra a giardíase.', 3, 12);

INSERT INTO SB_TB_VACCINE (name, species, description, first_dose_age_months, booster_interval_months)
VALUES ('V4 / V5 (Polivalente Felina)', 'Gato', 'Protege contra panleucopenia, rinotraqueíte, calicivirose e outras.', 2, 12);

INSERT INTO SB_TB_VACCINE (name, species, description, first_dose_age_months, booster_interval_months)
VALUES ('Leucemia Felina (FeLV)', 'Gato', 'Protege contra o vírus da leucemia felina.', 2, 12);