CREATE TABLE SB_TB_GUARDIAN (
                                id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                name VARCHAR2(255) NOT NULL,
                                email VARCHAR2(255) NOT NULL,
                                password VARCHAR2(255) NOT NULL,
                                user_type VARCHAR2(255) NOT NULL,
                                CONSTRAINT pk_guardian PRIMARY KEY (id),
                                CONSTRAINT uk_guardian_email UNIQUE (email)
);

CREATE TABLE SB_TB_ANIMAL (
                              id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              name VARCHAR2(255) NOT NULL,
                              species VARCHAR2(255) NOT NULL,
                              age NUMBER(10) NOT NULL,
                              weight NUMBER(10, 2) NOT NULL,
                              guardian_id NUMBER(10) NOT NULL,
                              CONSTRAINT pk_animal PRIMARY KEY (id),
                              CONSTRAINT fk_animal_guardian
                                  FOREIGN KEY (guardian_id) REFERENCES SB_TB_GUARDIAN(id)
);

CREATE TABLE SB_TB_CLINIC (
                              id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              name VARCHAR2(255) NOT NULL,
                              address VARCHAR2(255) NOT NULL,
                              phone VARCHAR2(255) NOT NULL,
                              CONSTRAINT pk_clinic PRIMARY KEY (id)
);

CREATE TABLE SB_TB_APPOINTMENT (
                                   id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   appointment_date VARCHAR2(255) NOT NULL,
                                   appointment_time VARCHAR2(255) NOT NULL,
                                   status VARCHAR2(255) NOT NULL,
                                   animal_id NUMBER(10) NOT NULL,
                                   clinic_id NUMBER(10) NOT NULL,
                                   CONSTRAINT pk_appointment PRIMARY KEY (id),
                                   CONSTRAINT fk_appointment_animal
                                       FOREIGN KEY (animal_id) REFERENCES SB_TB_ANIMAL(id),
                                   CONSTRAINT fk_appointment_clinic
                                       FOREIGN KEY (clinic_id) REFERENCES SB_TB_CLINIC(id)
);

CREATE TABLE SB_TB_CHECK_UP (
                                id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                check_up_type VARCHAR2(255) NOT NULL,
                                check_up_date VARCHAR2(255) NOT NULL,
                                status VARCHAR2(255) NOT NULL,
                                notes VARCHAR2(255) NOT NULL,
                                animal_id NUMBER(10) NOT NULL,
                                CONSTRAINT pk_check_up PRIMARY KEY (id),
                                CONSTRAINT fk_check_up_animal
                                    FOREIGN KEY (animal_id) REFERENCES SB_TB_ANIMAL(id)
);

CREATE TABLE SB_TB_HISTORY (
                               id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               description VARCHAR2(255) NOT NULL,
                               type VARCHAR2(255) NOT NULL,
                               record_date VARCHAR2(255) NOT NULL,
                               animal_id NUMBER(10) NOT NULL,
                               CONSTRAINT pk_history PRIMARY KEY (id),
                               CONSTRAINT fk_history_animal
                                   FOREIGN KEY (animal_id) REFERENCES SB_TB_ANIMAL(id)
);